project 3/auctions/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("categories", views.categories, name="categories"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("items/", include('item.urls')),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("<str:category>", views.category_items, name="category_items"),

]

urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

project 3/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

project 3/item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path("add/", views.add, name="add"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/add_Watchlist/", views.add_Watchlist, name="add_Watchlist"),
    path("<int:pk>/remove_Watchlist/", views.remove_Watchlist, name="remove_Watchlist"),
    path("<int:pk>/add_bid/", views.add_bid, name="add_bid"),
    path("<int:pk>/close_item/", views.close_item, name="close_item"),
    path("<int:pk>/add_comment/", views.add_comment, name="add_comment")
    ]

project 3/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    default_auto_field = 'django.db.models.AutoField'

project 3/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User
from item.models import Category, Item


def index(request):
    
    Items = Item.objects.filter(active=True).all()
    return render(request, "auctions/index.html", {
        'Items': Items
    })

def categories(request):
    return render(request, "auctions/categories.html", {
        "Categories": Category.objects.all()
    })    

def category_items(request, category):
    catid = Category.objects.get(name = category)
    return render(request, "auctions/index.html", {
        "Items": Item.objects.filter(category=catid.id, active=True).all(),
        "Category": Category.objects.get(id=catid.id)
    })

def watchlist(request):
    current_user = request.user
    Items = current_user.User_watchlist.all()
    return render(request, "auctions/index.html", {
        'Items': Items
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

project 3/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %} Categories {% endblock %}

{% block body %}
    
<div class="text-center">
  <h2>Categories</h2>
</div>
<br>
<div class="album py-5">
  <div class="container">
    <ul class="navbar-nav mr-auto " >
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">All categories</a>
      </li>
      {% for Category in Categories %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'category_items' Category.name  %}">{{ Category }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

project 3/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}


{% block title %} Active Listings {% endblock %}

{% block body %}
    <div class="text-center">
        <h2>Active Listings</h2>
    </div>
      <br>
      <div class="album py-5">
        <div class="container">
          <div class="row">
            {% for Item in Items %}
                <div class="col-md-4">
                  <a class= "card mb-4 box-shadow" href ="{% url 'item:detail' Item.id %}">
                    <img class="card-img-top" src="{{ Item.image }}">
                    <div class="card-body">
                      <p class=" text-muted"><h4>{{ Item.name }}</h4></p>
                      <p class="text-dark">{{ Item.description }}</p>
                      <small class="text-muted">
                        Price: <b>{{ Item.price }}$</b>
                      </small>
                    </div>
                  </a>
                </div>
            {% endfor %}
          </div>
        </div>
      </div>

{% endblock %}

project 3/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <title>{% block title %}{% endblock %} | Auction</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand navbar-light">
            <a class="navbar-brand text-primary" href="{% url 'index' %}"><b>Auction</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'item:add' %}">New item</a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                  </li>
                {% else %}
                      <a class="nav-item nav-link" href="{% url 'login' %}">Log In</a>
                      <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </ul>
              <span class="navbar-text">
                {% if user.is_authenticated %}
                    Signed in as &nbsp; <strong>{{ user.username }}</strong>.
                {% else %}
                    Not signed in.
                {% endif %}
              </span>
            </div>
          </nav>
          <hr>

          {% block body %}
          {% endblock %}

    </body>
</html>

project 3/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %} Log In {% endblock %}

{% block body %}

    
    <div class="text-center">
        <h2>Login</h2>
    </div>

    {% if message %}
        <div class="w-25 my-6 mx-auto">
            <div>{{ message }}</div>
        </div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="w-25 my-6 mx-auto">
            <div class="form-group">
                <div class="my-3">
                    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <div class="mb-3">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>  
            </div>
            <div class="form-group">        
                <div class="mb-3">
                    <input class="btn btn-primary btn-block mb-4" type="submit" value="Login">
                </div>
            </div>
            <div class="text-center">
                Don't have an account? <a href="{% url 'register' %}">Register here.</a>
            </div>     
        </div>
        
    </form>


{% endblock %}

project 3/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block title %} Register {% endblock %}

{% block body %}


<div class="text-center">
    <h2>Register</h2>
</div>


{% if message %}
    <div>{{ message }}</div>
{% endif %}

<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    <div class="w-25 mx-auto">
        <div class="form-group">
            <div class="mb-3">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
        </div>
        <div class="form-group">
            <div class="mb-3">
                <input autofocus class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
        </div>
        <div class="form-group">
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>  
        </div>
        <div class="form-group">
            <div class="mb-3">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>  
        </div>
        <div class="form-group">        
            <div class="mb-3">
                <input class="btn btn-primary btn-block mb-4" type="submit" value="Register">
            </div>
        </div>
        <div class="text-center">
            Already have an account? <a href="{% url 'login' %}">Log In here.</a>
        </div>       
    </div>
</form>

{% endblock %}