project 3/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

project 3/item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path("add/", views.add, name="add"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/add_Watchlist/", views.add_Watchlist, name="add_Watchlist"),
    path("<int:pk>/remove_Watchlist/", views.remove_Watchlist, name="remove_Watchlist"),
    path("<int:pk>/add_bid/", views.add_bid, name="add_bid"),
    path("<int:pk>/close_item/", views.close_item, name="close_item"),
    path("<int:pk>/add_comment/", views.add_comment, name="add_comment")
    ]

project 3/item/models.py
# from django.contrib.auth.models import User
from django.db import models

from auctions.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Item(models.Model):
    active = models.BooleanField(default=True)
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    price = models.FloatField()
    autor = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    watchlist = models.ManyToManyField(User, blank=True, related_name="User_watchlist")
    bid_by = models.ForeignKey(User, related_name='bids', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='item_comment', on_delete=models.CASCADE)
    message = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.user} comment on {self.item}"

project 3/item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'form-control'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
             'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
             'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })

        }

project 3/item/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponseRedirect, HttpResponse

from .forms import NewItemForm
from .models import Item, Comment


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    current_user = request.user
    item_in_watchlist = current_user in item.watchlist.all()
    comments = Comment.objects.filter(item=item).all()
    bid_by = item.bid_by
    if item.autor == current_user:
        owner = True
    else:
        owner = False
    if item.active == False:
        if bid_by != owner and bid_by == current_user:
            return render(request, 'item/detail.html', {
                'Item': item,
                'item_in_watchlist': item_in_watchlist,
                'owner': owner,
                'comments': comments,
                'message' : "Congratulate!You won this item"
            })
    else:
        return render(request, 'item/detail.html', {
            'Item': item,
            'item_in_watchlist': item_in_watchlist,
            'owner': owner,
            'comments': comments
        })
    return render(request, 'item/detail.html', {
        'Item': item,
        'item_in_watchlist': item_in_watchlist,
        'owner': owner,
        'comments': comments
    })


def add_Watchlist(request, pk):
    item = get_object_or_404(Item, pk=pk)
    current_user = request.user
    item.watchlist.add(current_user)
    return HttpResponseRedirect(reverse("item:detail", args=(item.id,) ))


def remove_Watchlist(request, pk):
    item = get_object_or_404(Item, pk=pk)
    current_user = request.user
    item.watchlist.remove(current_user)
    return HttpResponseRedirect(reverse("item:detail", args=(item.id,) ))

def add_bid(request, pk):
    item = get_object_or_404(Item, pk=pk)
    current_price = item.price
    current_user = request.user
    item_in_watchlist = request.user in item.watchlist.all()
    comments = Comment.objects.filter(item=item).all()
    if item.autor == request.user:
        owner = True
    else:
        owner = False

    if request.method =='POST':
        bid = request.POST["bid"]
        if float(current_price) < float(bid):
            item.price = bid
            item.bid_by = current_user
            item.save()
            return HttpResponseRedirect(reverse("item:detail",   args=(item.id,) ))
        else:
            return render(request, 'item/detail.html', {
            'Item': item,
            'item_in_watchlist': item_in_watchlist,
            'owner': owner,
            'comments': comments,
            'message':  "Your bid must be higher than the previous!"
    })

    else:
        return HttpResponseRedirect(reverse("item:detail", args=(item.id,) ))


def close_item(request, pk):
    item = get_object_or_404(Item, pk=pk)

    if request.method =='POST':
        item.active = False
        item.save()
        return HttpResponseRedirect(reverse("item:detail", args=(item.id,) ))
    else:
        return HttpResponseRedirect(reverse("item:detail", args=(item.id,) ))


def add(request):

    if request.method =='POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.autor = request.user
            item.bid_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/add.html', {
            'form': form
        })


def add_comment(request, pk):
    item = get_object_or_404(Item, pk=pk)
    current_user = request.user
    massege = request.POST["new_comment"]

    if massege != "":
        new_comment = Comment(
            user = current_user,
            item = item,
            message = massege
        )

        new_comment.save()

    return HttpResponseRedirect(reverse("item:detail", args=(item.id,) ))

project 3/item/templates/item/add.html
{% extends "auctions/layout.html" %}

{% block title %} New item {% endblock %}

{% block body %}

    <div class="text-center">
        <h2>Add new item</h2>
    </div>
  
      <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="w-25 my-6 mx-auto">
          {{ form.as_p }}
          
          <button type="submit" class="btn btn-primary btn-block mb-4">Add</button>
        </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ feild.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>

      {% endif %}

    </form>

{% endblock %}

project 3/item/templates/item/detail.html
{% extends "auctions/layout.html" %}

{% block title %} {{ Item.name }} {% endblock %}

{% block body %}

<div class="container">
  {% if message %}
    <div class="alert alert-primary" role="alert">
      {{ message }}
    </div>
  {% endif %}
  <div class="form-group">
    <div class="row g-0">
      <div class="col-md-4">
        {% if Item.image %}
          <img src="{{ Item.image.url }}" class="img-fluid rounded-start" alt="...">
        {% endif %}
        {% if user.is_authenticated %}
          {% if item_in_watchlist %}
            <form action="{% url 'item:remove_Watchlist' Item.id  %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-block mb-4">Remove from watchlist</button>
            </form>
          {% else %}
            <form action="{% url 'item:add_Watchlist' Item.id %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block mb-4">Add to watchlist</button>
            </form>
          {% endif %}
        {% endif %}
        {% if Item.active %}
          {% if user.is_authenticated %}
            {% if owner %}
            <form action="{% url 'item:close_item' Item.id %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning btn-block mb-4">Close item</button>
            </form>
            {% endif %}
          {% endif %}
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h3 class="card-title">{{ Item.name }}</h3>
          <p class="card-text">{{ Item.description }}</p>
          <p class="card-text"><small class="text-muted"> Current bid: <b>{{ Item.price }}$</b> </small></p>
          {% if Item.active %}
            {% if user.is_authenticated %}
              <form action="{% url 'item:add_bid' Item.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                  <div class="col-sm-3">
                    <input class="form-control" required step="0.01" type="number" name="bid">
                  </div>
                  <div class="col-sm-2">
                    <button type="submit" class="btn btn-success btn-block mb-4">Bid on</button>
                  </div>
                </div>
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>


  <h2>Commets:</h2>

  {% if Item.active %}
    {% if user.is_authenticated %}
    <form action="{% url 'item:add_comment' Item.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="col-10">
          <input class="form-control" placeholder="Comment..." type="text" name="new_comment">
        </div>
        <div class="col-2">
          <button type="submit" class="btn btn-success btn-block mb-4">Add comment</button>
        </div>
      </div>
    </form>
    {% endif %}
  {% endif %}





    {% for comment in comments %}
      <div class="card mb-2">
        <h5 class="card-header">{{ comment.user }}</h5>
        <div class="card-body">
          <p class="card-text">{{ comment.message }}</p>

        </div>
      </div>
    {% endfor %}

</div>

{% endblock %}